--- 
- hosts: webservers
  user: admin
  sudo: True

  vars:
    app_name: tcom
    repo_url: git@github.com:emillon/tech.no.com.git
    repo_remote: origin
    repo_version: master
    webapps_dir: /srv/webapps
    wsgi_callable: app
    wsgi_file: app.py
    server_name: tech.no.com
    virtualenv_dir: "{{webapps_dir}}/{{app_name}}/venv"

  tasks:
    - name: ensure log directory
      action: file dest={{webapps_dir}}/{{app_name}}/log state=directory

    - name: deploy code from repository
      action: git
      args:
          repo: "{{repo_url}}"
          dest: "{{webapps_dir}}/{{app_name}}/src"
          remote: "{{repo_remote}}"
          version: "{{repo_version}}"
          key_file: /home/admin/.ssh/id_rsa
      notify:
        - restart app

    - name: install dependencies into virtualenv
      action: pip
      args:
          requirements: "{{webapps_dir}}/{{app_name}}/src/requirements.txt"
          virtualenv: "{{virtualenv_dir}}"
          state: present

    - name: install site package
      action: pip
      args:
          name: .
          chdir: "{{webapps_dir}}/{{app_name}}/src"
          virtualenv: "{{virtualenv_dir}}"
          state: present

    - name: create supervisor program config
      action: template
      args:
          src: templates/supervisor.conf
          dest: /etc/supervisor/conf.d/{{app_name}}.conf
      notify:
        - restart app

    - name: create nginx site config
      action: template
      args:
          src: templates/nginx_site.conf
          dest: /etc/nginx/sites-available/{{app_name}}.conf
      notify:
        - restart nginx

    - name: link nginx config
      action: file
      args:
          src: /etc/nginx/sites-available/{{app_name}}.conf
          dest: /etc/nginx/sites-enabled/{{app_name}}.conf
          state: link

    - name: start app
      action: supervisorctl name={{app_name}} state=started

  handlers:
    - name: restart app
      action: supervisorctl name={{app_name}} state=restarted

    - name: restart nginx
      action: service name=nginx state=restarted
