language: python
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install coveralls --use-mirrors"
python:
  - "2.7"
script: "nosetests --with-coverage --cover-package=app"
after_success:
  coveralls
