language: python
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r requirements-dev.txt --use-mirrors"
  - "python setup.py develop"
  - "pip install coveralls --use-mirrors"
python:
  - "2.7"
script:
  - ./scripts/yaml_check
  - "nosetests --with-coverage --cover-package=app"
after_success:
  coveralls
